b站内容名字对应路径字典 = {'你的名字电影b站链接':'https://www.bilibili.com/bangumi/play/ss12044/?from=search&seid=6189233520511773441',
                         '让子弹飞电影b站链接':'https://www.bilibili.com/bangumi/play/ss12548/?from=search&seid=9278320401439128218',
                         '星际穿越电影b站链接':'https://www.bilibili.com/bangumi/play/ep285026?theme=movie&spm_id_from=333.851.b_62696c695f7265706f72745f6d6f766965.6',
                         '唐人街探案3电影b站链接':'https://www.bilibili.com/bangumi/play/ss38663?theme=movie&spm_id_from=333.851.b_62696c695f7265706f72745f6d6f766965.49',
                         '唐探3电影b站链接':'https://www.bilibili.com/bangumi/play/ss38663?theme=movie&spm_id_from=333.851.b_62696c695f7265706f72745f6d6f766965.49',
                         '哪吒之童魔降世':'https://www.bilibili.com/bangumi/play/ss28746/?from=search&seid=15346415849232487998',
                         '罗小黑战记':'https://www.bilibili.com/bangumi/play/ss28198/?from=search&seid=15346415849232487998'}

爱奇艺内容名字对应路径字典 = {'料理鼠王电影爱奇艺链接':'https://www.iqiyi.com/v_19rrjpxwpk.html',
                            '觉醒年代电视剧爱奇艺链接':'https://www.iqiyi.com/a_19rrhymcsx.html',
                            '山海情电视剧爱奇艺链接':'https://www.iqiyi.com/a_22e55c1zarp.html',
                            '泰坦尼克号电影爱奇艺链接':'https://www.iqiyi.com/v_19rrny4w8w.html',
                            '夏洛特烦恼电影爱奇艺链接':'https://www.iqiyi.com/lib/m_207267414.html?src=search',
                            '当幸福来敲门电影爱奇艺链接':'https://www.iqiyi.com/v_19rrk3nlys.html',
                            '邪不压正电影爱奇艺链接':'https://www.iqiyi.com/v_19rrfcw5e8.html',
                            '一步之遥电影爱奇艺链接':'https://www.iqiyi.com/v_19rrifwx53.html',
                            '关云长电影爱奇艺链接':'https://www.iqiyi.com/v_19rrjaeap4.html',
                            '太阳照常升起电影爱奇艺链接':'https://www.iqiyi.com/v_19rrj5vofo.html',
                            '八恶人电影爱奇艺链接':'https://www.iqiyi.com/v_19rr7q0bwk.html',}

落霞小说鲲弩小说路径字典 = {'简爱':'https://www.kunnu.com/jianai/',
                           '人类群星闪耀时':'https://www.kunnu.com/qunxing/',
                           '小王子':'https://www.kunnu.com/xiaowangzi/',
                           '鼠疫':'https://www.kunnu.com/shuyi/',
                           '了不起的盖茨比':'https://www.kunnu.com/gatsby/',
                           '巴黎圣母院':'https://www.kunnu.com/bali/',
                           '睡美人':'https://www.kunnu.com/shuimeiren/',
                           '傲慢与偏见':'https://www.kunnu.com/aoman/',
                           '百年孤独':'https://www.kunnu.com/bainiangudu/',
                           '海底两万里':'https://www.kunnu.com/haidiliangwanli/',
                           '杀死一只知更鸟':'https://www.kunnu.com/zhigengniao/',
                           '荒原狼':'https://www.kunnu.com/huangyuanlang/',
                           '查令十字街84号':'https://www.kunnu.com/chalingshizijie/',
                           '月亮和六便士':'https://www.kunnu.com/liubianshi/',
                           '西游记':'https://www.kunnu.com/xiyouji/',
                           '水浒传':'https://www.kunnu.com/shuihuzhuan/',
                           '围城':'https://www.kunnu.com/weicheng/',
                           '基督山伯爵':'https://www.kunnu.com/jidushan/',
                           '红楼梦':'https://www.kunnu.com/hongloumeng/',
                           '白鹿原':'https://www.kunnu.com/bailuyuan/',
                           '平凡的世界':'https://www.kunnu.com/pingfan/',
                           '我是猫':'https://www.kunnu.com/woshimao/',
                           '三体':'https://www.kunnu.com/santi/',
                           '球状闪电':'https://www.kunnu.com/qiuzhuangshandian/'}

